import Head from "next/head";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import MenuScroll from "@/components/MenuScroll";
import Backgroundimage from "@/components/Backgroundimage";
import Preference from "@/components/Preference";
import Footer from "@/components/Footer";
import TestimonialSection from "@/components/TestimonialSection";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>MealFlow - Healthy Meal Delivery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div
        style={{
          backgroundImage:
            "url('https://mealflow.com/public/img/bgpatern.webp')",
          height: "auto",
          width: "auto",
          backgroundColor: "white",
        }}
      >
        <Navbar />
        {/* <Contact /> */}
        <MenuScroll />
        <Backgroundimage />
        <Preference />
        <TestimonialSection />
        <Footer />
      </div>
    </>
  );
}
